import { BASIC_SKILLS, CHARACTERISTICS, CLASS_CAREERS, EMPTY_STATE, ROW_SCHEMAS } from './data.js';
import { evaluateD100Check, resolveDuration, resolveTalentMaximum } from './formulas.js';
import CAREERS from './data/careers.json' with { type: 'json' };
import SKILLS from './data/skills.json' with { type: 'json' };
import TALENTS from './data/talents.json' with { type: 'json' };
import SPELLS from './data/spells.json' with { type: 'json' };

const STORAGE_KEY='wfrp4-character-v1',DISCORD_STORAGE_KEY='wfrp4-discord-webhook-v1',THEME_STORAGE_KEY='wfrp4-theme-v1',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v));
const careerMap=new Map(CAREERS.map(x=>[x.name,x])),skillMap=new Map(SKILLS.map(x=>[norm(x.name),x])),talentMap=new Map(TALENTS.map(x=>[norm(x.name),x]));
const spellMap=new Map(SPELLS.map(x=>[norm(x.name),x]));
const basicMap=new Map(BASIC_SKILLS.map(([name,characteristic],index)=>[norm(name),{name,characteristic,index}]));
const aliases={'наблюдательность':'восприятие','уклонение':'уворот','кутёж':'сопротивление алкоголю','сплетничество':'сбор слухов','искусство':'изобразительное искусство','усмирение животных':'приручение','рукопашный бой':'рукопашное'};
const characteristicNames={'навык рукопашной':'ws','ближний бой':'ws','навык стрельбы':'bs','дальний бой':'bs','дистанционный бой':'bs','сила':'s','выносливость':'t','инициатива':'i','ловкость':'ag','проворство':'dex','интеллект':'int','сила воли':'wp','общительность':'fel','харизма':'fel'};
const speciesAliases={
  'human':'Человек','humans':'Человек','люди':'Человек','человек':'Человек',
  'dwarf':'Дварф','dwarfs':'Дварф','дворф':'Дварф','дварф':'Дварф',
  'halfling':'Полурослик','halflings':'Полурослик','полурослик':'Полурослик',
  'elf':'Высший эльф','high elf':'Высший эльф','высший эльф':'Высший эльф',
  'wood elf':'Лесной эльф','лесной эльф':'Лесной эльф',
  'gnome':'Гном','гном':'Гном','ogre':'Огр','огр':'Огр',
};
const speciesSilhouettes={
  'человек':['human','человека'],'дварф':['dwarf','дварфа'],'полурослик':['halfling','полурослика'],
  'высший эльф':['elf','высшего эльфа'],'лесной эльф':['elf','лесного эльфа'],
  'гном':['gnome','гнома'],'огр':['ogre','огра'],
};
let state=clone(EMPTY_STATE),saveTimer,cropDraft=null,cropDrag=null,context={characteristics:new Set(),skills:new Set(),talents:new Set()};
function norm(v){return String(v||'').trim().toLocaleLowerCase('ru-RU')} function base(v){return norm(v).replace(/\s*\([^)]*\)\s*$/,'').trim()} function num(v){return Number(v)||0}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function get(o,p){return p.split('.').reduce((v,k)=>v?.[k],o)} function set(o,p,v){const ks=p.split('.');let t=o;ks.slice(0,-1).forEach(k=>t=t[k]??={});t[ks.at(-1)]=v}
function activeTheme(){return document.documentElement.dataset.theme==='dark'?'dark':'light'}
function applyTheme(theme,persist=true){const dark=theme==='dark',value=dark?'dark':'light';document.documentElement.dataset.theme=value;const meta=$('meta[name="theme-color"]');if(meta)meta.content=dark?'#10110f':'#171411';$$('[data-theme-toggle]').forEach(button=>{button.textContent=dark?'☀ Дневная тема':'☾ Ночная тема';button.setAttribute('aria-pressed',String(dark));button.title=dark?'Переключить на дневную тему':'Переключить на ночную тему'});if(persist){try{localStorage.setItem(THEME_STORAGE_KEY,value)}catch{}}}
function toggleTheme(){applyTheme(activeTheme()==='dark'?'light':'dark')}
let themeBeforePrint='';
window.addEventListener('beforeprint',()=>{themeBeforePrint=activeTheme();applyTheme('light',false)});
window.addEventListener('afterprint',()=>{if(themeBeforePrint)applyTheme(themeBeforePrint,false);themeBeforePrint=''});
window.addEventListener('storage',event=>{if(event.key===THEME_STORAGE_KEY&&(event.newValue==='dark'||event.newValue==='light'))applyTheme(event.newValue,false)});
function basic(name){const n=norm(name),a=aliases[n]||n;return basicMap.get(a)||(!n.includes('(')?basicMap.get(base(a)):null)}
function skillRef(name){const n=norm(name);return [n,aliases[n],base(n),aliases[base(n)]].filter(Boolean).map(x=>skillMap.get(x)).find(Boolean)}
function talentRef(name){return talentMap.get(norm(name))||talentMap.get(base(name))} function charRef(item){return characteristicNames[norm(item?.characteristicName)]||''}

function populateClasses(selected=''){$('#class-select').innerHTML='<option value="">Выберите класс</option>'+Object.keys(CLASS_CAREERS).map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('')}
function populateCareers(cls,selected=''){const a=CLASS_CAREERS[cls]||[],s=$('#career-select');s.disabled=!a.length;s.innerHTML=`<option value="">${a.length?'Выберите карьеру':'Сначала выберите класс'}</option>`+a.map(n=>`<option ${n===selected?'selected':''}>${esc(n)}</option>`).join('');$('#career-level-select').disabled=!selected}
function charValue(k){const x=state.characteristics[k]||{};return num(x.initial)+num(x.advances)}
function charBonus(k){return Math.floor(charValue(k)/10)}
function canonicalSpecies(value){return speciesAliases[norm(value)]||value||''}
function updateSilhouette(){const image=$('#hit-silhouette');if(!image)return;const [asset,label]=speciesSilhouettes[norm(state.identity.species)]||['human','человека'];image.src=`./assets/silhouettes/${asset}.png`;image.alt=`Силуэт ${label}`;image.dataset.species=asset}
function clamp(value,min,max){return Math.min(max,Math.max(min,Number(value)||0))}
function normalizedCrop(value=state.portrait?.crop){return{x:clamp(value?.x,-100,100),y:clamp(value?.y,-100,100),zoom:clamp(value?.zoom||1,1,3)}}
function portraitTransform(crop=normalizedCrop()){return `scale(${crop.zoom}) translate(${crop.x/crop.zoom}%, ${crop.y/crop.zoom}%)`}
function applyPortraitTransform(image,crop=normalizedCrop()){if(image)image.style.transform=portraitTransform(crop)}
function hasPortrait(){return /^data:image\/(?:png|jpe?g|webp);base64,/i.test(String(state.portrait?.image||''))}
function renderDicePortrait(){const frame=$('#dice-result-avatar'),image=$('#dice-result-avatar-image'),visible=hasPortrait();frame.hidden=!visible;if(!visible){image.removeAttribute('src');return}image.src=state.portrait.image;applyPortraitTransform(image)}
function renderPortrait(){const visible=hasPortrait(),small=$('#portrait-small'),placeholder=$('#portrait-placeholder'),preview=$('#portrait-preview');small.hidden=!visible;placeholder.hidden=visible;preview.disabled=!visible;$('#portrait-edit').hidden=!visible;$('#portrait-remove').hidden=!visible;if(visible){small.src=state.portrait.image;$('#portrait-large').src=state.portrait.image;applyPortraitTransform(small)}else{small.removeAttribute('src');$('#portrait-large').removeAttribute('src')}renderDicePortrait()}
function loadImage(source){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('не удалось прочитать изображение'));image.src=source})}
function fileDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(Error('не удалось прочитать файл'));reader.readAsDataURL(file)})}
async function preparePortrait(file){if(file.size>16*1024*1024)throw Error('файл больше 16 МБ');if(file.type&&!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('нужен PNG, JPG или WEBP');const source=await fileDataUrl(file),image=await loadImage(source),limit=1400,scale=Math.min(1,limit/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const webp=canvas.toDataURL('image/webp',.86);return webp.startsWith('data:image/webp')?webp:canvas.toDataURL('image/jpeg',.88)}
function canvasBlob(canvas,type='image/png',quality=.92){return new Promise(resolve=>canvas.toBlob(resolve,type,quality))}
async function portraitThumbnailBlob(size=256){if(!hasPortrait())return null;try{const image=await loadImage(state.portrait.image),crop=normalizedCrop(),canvas=document.createElement('canvas'),context2d=canvas.getContext('2d');canvas.width=size;canvas.height=size;context2d.fillStyle='#1a1714';context2d.fillRect(0,0,size,size);const contain=Math.min(size/image.naturalWidth,size/image.naturalHeight),width=image.naturalWidth*contain*crop.zoom,height=image.naturalHeight*contain*crop.zoom,x=(size-width)/2+size*crop.x/100,y=(size-height)/2+size*crop.y/100;context2d.drawImage(image,x,y,width,height);return await canvasBlob(canvas)}catch{return null}}
function renderCropDraft(){if(!cropDraft)return;const image=$('#portrait-crop-image');image.src=state.portrait.image;applyPortraitTransform(image,cropDraft);$('#portrait-zoom').value=String(cropDraft.zoom)}
function openPortraitCrop(){if(!hasPortrait())return;cropDraft=normalizedCrop();renderCropDraft();$('#portrait-crop-dialog').showModal()}
function spellDurationDisplay(row){return resolveDuration(row?.duration,charBonus)||String(row?.duration||'')}
function renderCharacteristics(){$('#characteristics-table').innerHTML=`<table class="characteristics"><thead><tr><th></th>${CHARACTERISTICS.map(([k,s,l])=>`<th data-characteristic-col="${k}" title="${l}">${s}</th>`).join('')}</tr></thead><tbody>${[['initial','Начальные'],['advances','Повышение'],['current','Текущие']].map(([r,l])=>`<tr><th>${l}</th>${CHARACTERISTICS.map(([k])=>`<td data-characteristic-col="${k}">${r==='current'?`<output data-characteristic="${k}">0</output>`:`<input type="number" name="characteristics.${k}.${r}">`}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function renderBasic(){$('#basic-skills').innerHTML=`<div class="data-table skill-table"><div class="data-head"><span>Название</span><span>Хар.</span><span>Повыш.</span><span>Умение</span></div>${BASIC_SKILLS.map(([n,k],i)=>`<div class="data-row basic-skill-row" data-basic-skill-name="${esc(norm(n))}"><span data-ref-type="skill" data-ref-name="${esc(n)}">${esc(n)}</span><output data-skill-characteristic="${k}">0</output><input type="number" name="basicSkills.${i}.advances"><output data-basic-skill="${i}">0</output></div>`).join('')}</div>`}
function renderSpellRows(){const target=$('#spells'),rows=state.spells||[];const body=rows.map((row,i)=>`<article class="spell-entry"><div class="spell-row"><input data-row-field="spells.${i}.name" data-ref-type="spell" data-ref-name="${esc(row.name)}" value="${esc(row.name)}" aria-label="Название"><input data-row-field="spells.${i}.cn" value="${esc(row.cn)}" aria-label="Цена"><input data-row-field="spells.${i}.range" value="${esc(row.range)}" aria-label="Дальность"><input data-row-field="spells.${i}.target" value="${esc(row.target)}" aria-label="Цель"><input data-row-field="spells.${i}.duration" value="${esc(row.duration)}" aria-label="Длительность"><button type="button" class="remove-row" data-remove="spells" data-index="${i}" aria-label="Удалить заклинание">×</button></div><div class="spell-details">${row.school||row.source?`<p class="spell-meta">${esc(row.school||'')}${row.school&&row.source?' · ':''}${esc(row.source||'')}</p>`:''}<label>Эффект<textarea data-row-field="spells.${i}.effect" rows="4">${esc(row.effect)}</textarea></label></div></article>`).join('');target.innerHTML=`<div class="spell-table"><div class="spell-head"><span>Название</span><span>Цена</span><span>Дальность</span><span>Цель</span><span>Длительность</span><span></span></div>${body||'<p class="empty-row">Пока нет записей</p>'}</div>`}
function renderRows(type){if(type==='spells'){renderSpellRows();return}const target=$(`#${type==='skills'?'advanced-skills':type}`);if(!target)return;const schema=ROW_SCHEMAS[type],rows=state[type]||[],head=schema.map(([,l])=>`<span>${l}</span>`).join('')+'<span></span>';const body=rows.map((row,i)=>{const rt=type==='skills'?'skill':type==='talents'?'talent':'',avail=type==='skills'?context.skills.has(norm(row.name)):type==='talents'?context.talents.has(norm(row.name)):false;return `<div class="data-row dynamic-row ${avail?'career-available':''}">${schema.map(([k,l,kind])=>{if(kind==='output')return `<output data-row-output="${type}.${i}.${k}">0</output>`;if(kind==='select')return `<select data-row-field="${type}.${i}.${k}" aria-label="${l}"><option value="">—</option>${CHARACTERISTICS.map(([v,s,n])=>`<option value="${v}" title="${esc(n)}" ${row[k]===v?'selected':''}>${s}</option>`).join('')}</select>`;const ref=rt&&k==='name'?` data-ref-type="${rt}" data-ref-name="${esc(row[k])}"`:'';const title=k==='name'?` title="${esc(row[k])}"`:'';return `<input ${kind==='number'?'type="number"':''} data-row-field="${type}.${i}.${k}" value="${esc(row[k])}" aria-label="${l}"${title}${ref}>`}).join('')}<button type="button" class="remove-row" data-remove="${type}" data-index="${i}">×</button></div>`}).join('');target.innerHTML=`<div class="data-table schema-${type}" style="--columns:${schema.map(x=>x[2]==='select'?'76px':x[2]==='number'||x[2]==='output'?'72px':'minmax(170px,1fr)').join(' ')} 34px"><div class="data-head">${head}</div>${body||'<p class="empty-row">Пока нет записей</p>'}</div>`}
function renderAll(){Object.keys(ROW_SCHEMAS).forEach(renderRows)}
function calculate(){CHARACTERISTICS.forEach(([k])=>$$(`[data-characteristic="${k}"],[data-skill-characteristic="${k}"]`).forEach(e=>e.textContent=charValue(k)));BASIC_SKILLS.forEach(([,k],i)=>{const e=$(`[data-basic-skill="${i}"]`);if(e)e.textContent=charValue(k)+num(get(state,`basicSkills.${i}.advances`))});state.skills.forEach((x,i)=>{const e=$(`[data-row-output="skills.${i}.value"]`);if(e)e.textContent=charValue(x.characteristic)+num(x.advances)});$('[data-output="experience.total"]').textContent=num(state.experience.current)+num(state.experience.spent);$('[data-output="movement.walk"]').textContent=num(state.movement.value)*2;$('[data-output="movement.run"]').textContent=num(state.movement.value)*4;const s=Math.floor(charValue('s')/10),t=Math.floor(charValue('t')/10),w=Math.floor(charValue('wp')/10),h=state.talents.reduce((a,x)=>a+(norm(x.name)==='стойкий'?Math.max(1,num(x.taken)):0),0);$('[data-output="wounds.max"]').textContent=s+2*t+w+h*t;$('#wounds-formula').textContent=`БСил ${s} + 2×БВын ${t} + БСВ ${w}${h?` + Стойкий ${h}×БВын`:''}`}

const legacyRenderRows=renderRows,legacyCalculate=calculate;
function renderCharacteristicsEnhanced(){$('#characteristics-table').innerHTML=`<table class='characteristics'><thead><tr><th></th>${CHARACTERISTICS.map(([k,s,l])=>`<th data-characteristic-col='${k}' title='${esc(l)}'><span>${s}</span><button type='button' class='inline-roll' data-roll-characteristic='${k}' title='Бросок d100' aria-label='Бросить проверку: ${esc(l)}'>◆</button></th>`).join('')}</tr></thead><tbody>${[['initial','Начальные'],['advances','Повышение'],['current','Текущие']].map(([r,l])=>`<tr><th>${l}</th>${CHARACTERISTICS.map(([k])=>`<td data-characteristic-col='${k}'>${r==='current'?`<output data-characteristic='${k}'>0</output>`:`<input type='number' name='characteristics.${k}.${r}'>`}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function renderBasicEnhanced(){$('#basic-skills').innerHTML=`<div class='data-table skill-table'><div class='data-head'><span>Название</span><span>Хар.</span><span>Повыш.</span><span>Умение</span></div>${BASIC_SKILLS.map(([n,k],i)=>`<div class='data-row basic-skill-row' data-basic-skill-name='${esc(norm(n))}'><span class='skill-name-cell'><span data-ref-type='skill' data-ref-name='${esc(n)}'>${esc(n)}</span><button type='button' class='inline-roll' data-roll-basic='${i}' aria-label='Бросить проверку: ${esc(n)}'>◆</button></span><output data-skill-characteristic='${k}'>0</output><input type='number' name='basicSkills.${i}.advances'><output data-basic-skill='${i}'>0</output></div>`).join('')}</div>`}
function renderSpellRowsEnhanced(){const rows=state.spells||[],body=rows.map((row,i)=>`<article class='spell-entry'><div class='spell-row'><input data-row-field='spells.${i}.name' data-ref-type='spell' data-ref-name='${esc(row.name)}' value='${esc(row.name)}' aria-label='Название'><input data-row-field='spells.${i}.cn' value='${esc(row.cn)}' aria-label='Цена'><input data-row-field='spells.${i}.range' value='${esc(row.range)}' aria-label='Дальность'><input data-row-field='spells.${i}.target' value='${esc(row.target)}' aria-label='Цель'><div class='duration-cell'><input data-row-field='spells.${i}.duration' data-spell-duration-input='${i}' value='${esc(spellDurationDisplay(row))}' aria-label='Длительность'></div><button type='button' class='remove-row' data-remove='spells' data-index='${i}' aria-label='Удалить заклинание'>×</button></div><details class='entry-details'><summary>Эффект и описание</summary><div class='entry-details-body'>${row.school||row.source?`<p class='spell-meta'>${esc(row.school||'')}${row.school&&row.source?' · ':''}${esc(row.source||'')}</p>`:''}<label>Эффект<textarea data-row-field='spells.${i}.effect' rows='5'>${esc(row.effect)}</textarea></label></div></details></article>`).join('');$('#spells').innerHTML=`<div class='spell-table'><div class='spell-head'><span>Название</span><span>Цена</span><span>Дальность</span><span>Цель</span><span>Длительность</span><span></span></div>${body||'<p class="empty-row">Пока нет записей</p>'}</div>`}
function renderTalentRowsEnhanced(){const rows=state.talents||[],body=rows.map((row,i)=>`<article class='talent-entry ${context.talents.has(norm(row.name))?'career-available':''}'><div class='talent-row'><input data-row-field='talents.${i}.name' data-ref-type='talent' data-ref-name='${esc(row.name)}' value='${esc(row.name)}' aria-label='Название'><label class='talent-taken' aria-label='Взятий из максимума'><input type='number' min='0' data-row-field='talents.${i}.taken' value='${esc(row.taken??0)}'><span>/ <output data-talent-maximum='${i}'>—</output></span></label><input data-row-field='talents.${i}.checks' value='${esc(row.checks||'')}' aria-label='Проверки' placeholder='Проверки'><button type='button' class='remove-row' data-remove='talents' data-index='${i}' aria-label='Удалить талант'>×</button></div><p class='talent-meta'>Максимум: ${esc(row.maximumFormula||'—')}${row.source?` · ${esc(row.source)}`:''}</p><details class='entry-details'><summary>Описание таланта</summary><div class='entry-details-body'><textarea data-row-field='talents.${i}.description' rows='5' aria-label='Описание таланта'>${esc(row.description||'')}</textarea></div></details></article>`).join('');$('#talents').innerHTML=`<div class='talent-table'><div class='talent-head'><span>Название</span><span>Взятий / макс.</span><span>Проверки</span><span></span></div>${body||'<p class="empty-row">Пока нет записей</p>'}</div>`}
function enhanceAdvancedSkillRolls(){$$(`input[data-row-field^='skills.'][data-row-field$='.name']`).forEach(input=>{if(input.parentElement.classList.contains('skill-name-input'))return;const match=input.dataset.rowField.match(/^skills\.(\d+)\.name$/);if(!match)return;const wrap=document.createElement('div'),button=document.createElement('button');wrap.className='skill-name-input';button.type='button';button.className='inline-roll';button.dataset.rollAdvanced=match[1];button.textContent='◆';button.setAttribute('aria-label',`Бросить проверку: ${input.value||'умение'}`);input.before(wrap);wrap.append(input,button)})}
renderCharacteristics=renderCharacteristicsEnhanced;
renderBasic=renderBasicEnhanced;
renderRows=function(type){if(type==='spells')renderSpellRowsEnhanced();else if(type==='talents')renderTalentRowsEnhanced();else{legacyRenderRows(type);if(type==='skills')enhanceAdvancedSkillRolls()}};
calculate=function(){legacyCalculate();state.talents.forEach((row,i)=>{const out=$(`[data-talent-maximum='${i}']`);if(out)out.textContent=resolveTalentMaximum(row.maximumFormula,charBonus).display});state.spells.forEach((row,i)=>{const input=$(`[data-spell-duration-input='${i}']`);if(input&&input!==document.activeElement)input.value=spellDurationDisplay(row)});updateSilhouette()};

function ensureSkill(x){const b=basic(x.name);if(b&&!String(x.name).includes('('))return;if(state.skills.some(y=>norm(y.name)===norm(x.name)))return;state.skills.push({name:x.name,characteristic:x.characteristic||charRef(skillRef(x.name)),advances:0,fromCareer:true})}
function updateHighlights(){$$('[data-characteristic-col]').forEach(e=>e.classList.toggle('career-available',context.characteristics.has(e.dataset.characteristicCol)));$$('.basic-skill-row').forEach(e=>e.classList.toggle('career-available',context.skills.has(e.dataset.basicSkillName)))}
function showPage(p){$$('.tab').forEach(e=>e.classList.toggle('is-active',e.dataset.page===p));$$('.sheet').forEach(e=>e.classList.toggle('is-active',e.dataset.sheetPage===p))}
function updateArcane(c){const mode=c?.arcanePage||'',tab=$('#arcane-tab');tab.hidden=!mode;$('#open-spell-catalog').hidden=mode!=='spells';if(!mode){if(tab.classList.contains('is-active'))showPage('1');return}const title=mode==='prayers'?'Молитвы':'Заклинания';tab.textContent=title;$('#arcane-page-title').textContent=title;$('#arcane-section-title').textContent=title;$('#arcane-page-subtitle').textContent=mode==='prayers'?'Благословения и чудеса':'Магия и заклинания'}
function applyCareer(add=true){const c=careerMap.get(state.identity.career),level=Math.max(0,Math.min(4,num(state.identity.careerLevel)));context={characteristics:new Set(),skills:new Set(),talents:new Set()};updateArcane(c);if(!c||!level){state.identity.careerPath='';state.identity.status=''}else{const current=c.levels[level-1];state.identity.careerPath=current?.path||'';state.identity.status=current?.status||'';Object.entries(c.development||{}).forEach(([k,n])=>{if(num(n)<=level)context.characteristics.add(k)});c.levels.slice(0,level).forEach(stage=>{(stage.skills||[]).forEach(x=>{context.skills.add(norm(x.name));const b=basic(x.name);if(b&&!String(x.name).includes('('))context.skills.add(norm(b.name));if(add)ensureSkill(x)});(stage.talents||[]).forEach(x=>context.talents.add(norm(x.name)))})}$('#career-path').value=state.identity.careerPath;$('#career-status').value=state.identity.status;renderRows('skills');renderRows('talents');updateHighlights();calculate()}
function migrate(x){if(!x||typeof x!=='object')throw Error('Файл не содержит персонажа.');const r={...clone(EMPTY_STATE),...x,version:6};['identity','characteristics','resources','experience','movement','ambitions','party','armourPoints','wealth','wounds'].forEach(k=>r[k]={...(EMPTY_STATE[k]||{}),...(x[k]||{})});r.portrait={...clone(EMPTY_STATE.portrait),...(x.portrait||{})};r.portrait.crop=normalizedCrop(x.portrait?.crop||EMPTY_STATE.portrait.crop);if(!/^data:image\/(?:png|jpe?g|webp);base64,/i.test(String(r.portrait.image||'')))r.portrait.image='';r.identity.species=canonicalSpecies(r.identity.species);Object.keys(ROW_SCHEMAS).forEach(k=>r[k]=Array.isArray(x[k])?x[k]:[]);return r}
function enrichSavedSpells(){state.spells.forEach(row=>{const x=spellMap.get(norm(row.name));if(!x)return;const oldMeta=[x.school,x.source].filter(Boolean).join(' · ');if(!row.range)row.range=x.range;if(!row.target)row.target=x.target;if(!row.duration)row.duration=x.duration;if(!row.effect||row.effect===oldMeta||row.effect===x.school)row.effect=x.description||'';if(!row.school)row.school=x.school;if(!row.source)row.source=x.source;if(!row.cn)row.cn=x.castingNumber})}
function enrichSavedTalents(){state.talents.forEach(row=>{const x=talentRef(row.name);if(!x)return;const legacy=!Object.hasOwn(row,'maximumFormula');row.maximumFormula=x.maximum||'';row.checks=row.checks||x.checks||'';row.source=x.source||row.source||'';if(!row.description||legacy)row.description=x.description||''})}
function hydrate(){enrichSavedSpells();enrichSavedTalents();populateClasses(state.identity.class);populateCareers(state.identity.class,state.identity.career);$$('[name]',$('#character-form')).forEach(e=>e.value=get(state,e.name)??'');renderAll();renderPortrait();applyCareer();calculate()}
function save(){clearTimeout(saveTimer);$('#save-status').textContent='Сохранение…';saveTimer=setTimeout(()=>{state.updatedAt=new Date().toISOString();try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#save-status').textContent='Сохранено'}catch{$('#save-status').textContent='Не сохранено';toast('Браузеру не хватило места для арта. Скачайте JSON персонажа.')}},300)}
function closeDicePalette(){$('#dice-palette').hidden=true;$('#dice-launch').classList.remove('is-open')}
function openSheet(x){state=migrate(x);$('#welcome').hidden=true;$('#app').hidden=false;$('#dice-widget').classList.add('is-active');hydrate();save()} function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('is-visible');setTimeout(()=>e.classList.remove('is-visible'),2600)}

$('#new-character').onclick=()=>openSheet(clone(EMPTY_STATE));$('#continue-character').onclick=()=>openSheet(JSON.parse(localStorage.getItem(STORAGE_KEY)));$('#load-character').onclick=$('#import-character').onclick=()=>$('#file-input').click();$('#back-home').onclick=()=>{$('#app').hidden=true;$('#welcome').hidden=false;$('#dice-widget').classList.remove('is-active');closeDicePalette();$('#continue-character').hidden=!localStorage.getItem(STORAGE_KEY)};
$('#file-input').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{openSheet(JSON.parse(await f.text()));toast('Персонаж загружен')}catch(x){toast(`Не удалось загрузить: ${x.message}`)}e.target.value=''};
$('#export-character').onclick=()=>{const b=new Blob([JSON.stringify({...state,updatedAt:new Date().toISOString()},null,2)],{type:'application/json'}),a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(b),download:`${state.identity.name||'wfrp4-character'}.json`});a.click();URL.revokeObjectURL(a.href);toast('JSON сохранён')};
$('#portrait-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{$('#save-status').textContent='Обработка арта…';state.portrait={image:await preparePortrait(file),crop:{x:0,y:0,zoom:1}};renderPortrait();save();openPortraitCrop()}catch(error){toast(`Арт не загружен: ${error.message}`)}event.target.value=''};
$('#portrait-preview').onclick=()=>{if(hasPortrait()){$('#portrait-large').src=state.portrait.image;$('#portrait-viewer-dialog').showModal()}};
$('#portrait-edit').onclick=openPortraitCrop;
$('#portrait-edit-large').onclick=()=>{$('#portrait-viewer-dialog').close();openPortraitCrop()};
$('#portrait-remove').onclick=()=>{if(!hasPortrait()||!confirm('Удалить арт персонажа?'))return;state.portrait=clone(EMPTY_STATE.portrait);renderPortrait();save();toast('Арт удалён')};
$('#close-portrait-viewer').onclick=()=>$('#portrait-viewer-dialog').close();
$('#portrait-viewer-dialog').onclick=event=>{if(event.target===$('#portrait-viewer-dialog'))event.target.close()};
function closePortraitCrop(){$('#portrait-crop-dialog').close();cropDraft=null;cropDrag=null}
$('#close-portrait-crop').onclick=$('#portrait-cancel-crop').onclick=closePortraitCrop;
$('#portrait-crop-dialog').onclick=event=>{if(event.target===$('#portrait-crop-dialog'))closePortraitCrop()};
$('#portrait-reset-crop').onclick=()=>{cropDraft={x:0,y:0,zoom:1};renderCropDraft()};
$('#portrait-zoom').oninput=event=>{if(!cropDraft)return;cropDraft.zoom=clamp(event.target.value,1,3);renderCropDraft()};
$('#portrait-crop-form').onsubmit=event=>{event.preventDefault();if(!cropDraft)return;state.portrait.crop=normalizedCrop(cropDraft);renderPortrait();closePortraitCrop();save();toast('Кадр миниатюры сохранён')};
$('#portrait-crop-stage').addEventListener('pointerdown',event=>{if(!cropDraft||event.button!==0)return;event.preventDefault();cropDrag={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,x:cropDraft.x,y:cropDraft.y};event.currentTarget.setPointerCapture(event.pointerId)});
$('#portrait-crop-stage').addEventListener('pointermove',event=>{if(!cropDrag||cropDrag.pointerId!==event.pointerId||!cropDraft)return;const box=event.currentTarget.getBoundingClientRect();cropDraft.x=clamp(cropDrag.x+(event.clientX-cropDrag.startX)/box.width*100,-100,100);cropDraft.y=clamp(cropDrag.y+(event.clientY-cropDrag.startY)/box.height*100,-100,100);renderCropDraft()});
$('#portrait-crop-stage').addEventListener('pointerup',event=>{if(cropDrag?.pointerId===event.pointerId)cropDrag=null});
$('#portrait-crop-stage').addEventListener('pointercancel',()=>{cropDrag=null});
$('#character-form').addEventListener('input',e=>{if(e.target.name)set(state,e.target.name,e.target.type==='number'?(e.target.value===''?'':num(e.target.value)):e.target.value);if(e.target.id==='class-select'){Object.assign(state.identity,{career:'',careerLevel:'',careerPath:'',status:''});populateCareers(e.target.value);applyCareer()}if(e.target.id==='career-select'){Object.assign(state.identity,{careerLevel:'',careerPath:'',status:''});$('#career-level-select').value='';$('#career-level-select').disabled=!e.target.value;applyCareer()}if(e.target.id==='career-level-select')applyCareer();if(e.target.dataset.rowField){set(state,e.target.dataset.rowField,e.target.type==='number'?num(e.target.value):e.target.value);if(e.target.dataset.refType)e.target.dataset.refName=e.target.value}calculate();save()});
$('#character-form').addEventListener('focusout',e=>{if(e.target.matches('[data-spell-duration-input]'))setTimeout(calculate,0)});
document.addEventListener('click',e=>{const add=e.target.dataset.add;if(add==='skills')openSkillDialog();else if(add){state[add].push({});renderRows(add);calculate();save()}const rem=e.target.dataset.remove;if(rem){state[rem].splice(num(e.target.dataset.index),1);renderRows(rem);calculate();save()}if(e.target.matches('.tab')){showPage(e.target.dataset.page);scrollTo({top:0,behavior:'smooth'})}const ps=e.target.closest('[data-pick-skill]');if(ps){const x=SKILLS[num(ps.dataset.pickSkill)];$('#new-skill-name').value=x.name;$('#new-skill-characteristic').value=charRef(x)}const pt=e.target.closest('[data-add-talent]');if(pt)addTalent(TALENTS[num(pt.dataset.addTalent)])});

function renderSkillCatalog(q=''){const s=norm(q),a=SKILLS.filter(x=>!s||norm(x.name).includes(s));$('#skill-catalog-list').innerHTML=a.map(x=>{const i=SKILLS.indexOf(x);return `<button type="button" class="catalog-item ${context.skills.has(norm(x.name))?'career-available':''}" data-pick-skill="${i}"><strong>${esc(x.name)}</strong><small>${esc(x.characteristicName||'Характеристика не указана')}</small></button>`}).join('')||'<p class="empty-row">Ничего не найдено</p>'}
function openSkillDialog(){$('#skill-dialog-form').reset();$('#new-skill-advances').value=0;renderSkillCatalog();$('#skill-dialog').showModal()} function closeSkillDialog(){$('#skill-dialog').close()}
$('#skill-catalog-search').oninput=e=>renderSkillCatalog(e.target.value);$('#close-skill-dialog').onclick=$('#cancel-skill').onclick=closeSkillDialog;$('#skill-dialog').onclick=e=>{if(e.target===$('#skill-dialog'))closeSkillDialog()};$('#skill-dialog-form').onsubmit=e=>{e.preventDefault();const name=$('#new-skill-name').value.trim(),characteristic=$('#new-skill-characteristic').value;if(!name||!characteristic)return;if(state.skills.some(x=>norm(x.name)===norm(name)))toast('Это умение уже добавлено');else state.skills.push({name,characteristic,advances:num($('#new-skill-advances').value)});renderRows('skills');calculate();save();closeSkillDialog()};
function renderTalentCatalog(q=''){const s=norm(q),a=TALENTS.filter(x=>!s||norm(x.name).includes(s)||norm(x.nameEn).includes(s));$('#talent-catalog-list').innerHTML=a.map(x=>{const i=TALENTS.indexOf(x),added=state.talents.some(y=>norm(y.name)===norm(x.name));return `<article class="catalog-item talent-catalog-item ${context.talents.has(norm(x.name))?'career-available':''}" data-ref-type="talent" data-ref-name="${esc(x.name)}"><span><strong>${esc(x.name)}</strong><small>${esc(x.maximum||'')}${x.checks?` · ${esc(x.checks)}`:''}</small></span><button type="button" data-add-talent="${i}" ${added?'disabled':''}>${added?'Добавлен':'Добавить'}</button></article>`}).join('')||'<p class="empty-row">Ничего не найдено</p>'}
function addTalent(x){if(state.talents.some(y=>norm(y.name)===norm(x.name)))return;state.talents.push({name:x.name,taken:1,maximumFormula:x.maximum||'',checks:x.checks||'',description:x.description||'',source:x.source||''});renderRows('talents');renderTalentCatalog($('#talent-catalog-search').value);calculate();save()}
$('#open-talent-catalog').onclick=()=>{renderTalentCatalog();$('#talent-catalog-dialog').showModal()};$('#close-talent-catalog').onclick=()=>$('#talent-catalog-dialog').close();$('#talent-catalog-search').oninput=e=>renderTalentCatalog(e.target.value);$('#talent-catalog-dialog').onclick=e=>{if(e.target===$('#talent-catalog-dialog'))e.target.close()};
const spellSchools=[...new Set(SPELLS.map(x=>x.school).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));
$('#spell-school-filter').innerHTML='<option value="">Все школы</option>'+spellSchools.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');
function renderSpellCatalog(){const q=norm($('#spell-catalog-search').value),school=$('#spell-school-filter').value,items=SPELLS.filter(x=>(!q||norm(x.name).includes(q)||norm(x.nameEn).includes(q))&&(!school||x.school===school));$('#spell-catalog-count').textContent=`Найдено: ${items.length} из ${SPELLS.length}`;$('#spell-catalog-list').innerHTML=items.map(x=>{const i=SPELLS.indexOf(x),added=state.spells.some(y=>norm(y.name)===norm(x.name));return `<article class="catalog-item talent-catalog-item" data-ref-type="spell" data-ref-name="${esc(x.name)}"><span><strong>${esc(x.name)}</strong><small>${esc(x.school)} · ПС ${esc(x.castingNumber)}${x.source?` · ${esc(x.source)}`:''}</small></span><button type="button" data-add-spell="${i}" ${added?'disabled':''}>${added?'Добавлено':'Добавить'}</button></article>`}).join('')||'<p class="empty-row">Ничего не найдено</p>'}
function addSpell(x){if(state.spells.some(y=>norm(y.name)===norm(x.name)))return;state.spells.push({name:x.name,cn:x.castingNumber,range:x.range,target:x.target,duration:x.duration,effect:x.description||'',school:x.school,source:x.source});renderRows('spells');renderSpellCatalog();calculate();save()}
$('#open-spell-catalog').onclick=()=>{renderSpellCatalog();$('#spell-catalog-dialog').showModal()};$('#close-spell-catalog').onclick=()=>$('#spell-catalog-dialog').close();$('#spell-catalog-search').oninput=renderSpellCatalog;$('#spell-school-filter').onchange=renderSpellCatalog;$('#spell-catalog-dialog').onclick=e=>{if(e.target===$('#spell-catalog-dialog'))e.target.close()};
document.addEventListener('click',e=>{const p=e.target.closest('[data-add-spell]');if(p)addSpell(SPELLS[num(p.dataset.addSpell)])});
function showTip(t){const name=t.matches('input')?t.value:t.dataset.refName,type=t.dataset.refType,x=type==='skill'?skillRef(name):type==='spell'?spellMap.get(norm(name)):talentRef(name);if(!x)return;const duration=type==='spell'?(resolveDuration(x.duration,charBonus)||x.duration):'',p=$('#reference-tooltip'),dialog=t.closest('dialog');(dialog||document.body).append(p);p.innerHTML=type==='spell'?`<strong>${esc(x.name)}</strong><dl><dt>ПС:</dt><dd>${esc(x.castingNumber||'—')}</dd><dt>Дальность:</dt><dd>${esc(x.range||'—')}</dd><dt>Цель:</dt><dd>${esc(x.target||'—')}</dd><dt>Длительность:</dt><dd>${esc(duration||'—')}</dd></dl><b>Описание:</b><p>${esc(x.description||'Описание пока отсутствует.')}</p>`:`<strong>${esc(x.name)}</strong><p>${esc(x.description||'Описание пока отсутствует.')}</p>`;p.classList.add('is-visible');const r=t.getBoundingClientRect(),width=p.offsetWidth,height=p.offsetHeight;let left=r.right+10;if(left+width>innerWidth-12)left=r.left-width-10;let top=Math.min(innerHeight-height-12,Math.max(12,r.top));p.style.left=`${Math.max(12,left)}px`;p.style.top=`${top}px`} function hideTip(){$('#reference-tooltip').classList.remove('is-visible')}
document.addEventListener('mouseover',e=>{const t=e.target.closest('[data-ref-type]');if(t)showTip(t)});document.addEventListener('mouseout',e=>{if(e.target.closest('[data-ref-type]'))hideTip()});document.addEventListener('focusin',e=>{const t=e.target.closest('[data-ref-type]');if(t)showTip(t)});document.addEventListener('focusout',e=>{if(e.target.closest('[data-ref-type]'))hideTip()});

function randomDie(sides){const range=0x100000000,limit=range-range%sides,buffer=new Uint32Array(1);do crypto.getRandomValues(buffer);while(buffer[0]>=limit);return buffer[0]%sides+1}
function discordSettings(){try{return{enabled:false,webhookUrl:'',...JSON.parse(localStorage.getItem(DISCORD_STORAGE_KEY)||'{}')}}catch{return{enabled:false,webhookUrl:''}}}
function validWebhook(value){try{const url=new URL(String(value).trim()),host=url.hostname==='discord.com'||url.hostname.endsWith('.discord.com');return url.protocol==='https:'&&host&&/^\/api(?:\/v\d+)?\/webhooks\/\d+\/[^/?#]+$/.test(url.pathname)}catch{return false}}
function updateDiscordIndicator(){const settings=discordSettings();$('#dice-launch').classList.toggle('discord-connected',Boolean(settings.enabled&&settings.webhookUrl))}
function discordPayload(title,description,fields=[]){return{username:'WFRP Dice',allowed_mentions:{parse:[]},embeds:[{color:0x7a241e,author:{name:state.identity.name||'Персонаж WFRP'},title,description,fields,timestamp:new Date().toISOString()}]}}
async function postDiscord(payload,settings=discordSettings(),force=false){if(!force&&!settings.enabled)return false;if(!validWebhook(settings.webhookUrl))throw Error('неверный URL вебхука');const url=new URL(settings.webhookUrl);url.searchParams.set('wait','true');const portrait=await portraitThumbnailBlob(),body=JSON.parse(JSON.stringify(payload));let options;if(portrait){body.embeds[0].thumbnail={url:'attachment://character-portrait.png'};body.attachments=[{id:0,filename:'character-portrait.png',description:'Портрет персонажа'}];const form=new FormData();form.append('payload_json',JSON.stringify(body));form.append('files[0]',portrait,'character-portrait.png');options={method:'POST',body:form}}else options={method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};const response=await fetch(url,options);if(!response.ok)throw Error(`Discord вернул ${response.status}`);return true}
let rollSequence=0;
function openDicePalette(){$('#dice-palette').hidden=false;$('#dice-launch').classList.add('is-open')}
function presentRoll(text,id){const output=$('#dice-result');output.dataset.rollId=String(id);output.dataset.baseText=text;$('#dice-result-text').textContent=text;renderDicePortrait()}
function deliveryStatus(id,status){const output=$('#dice-result');if(output.dataset.rollId!==String(id))return;$('#dice-result-text').textContent=`${output.dataset.baseText}\n${status}`}
async function deliverRoll(payload,id){const settings=discordSettings();if(!settings.enabled)return;deliveryStatus(id,'Discord: отправка…');try{await postDiscord(payload,settings);deliveryStatus(id,'Discord: отправлено ✓')}catch(error){deliveryStatus(id,`Discord: ${error.message}`)}}
function rollPolyhedron(sides){const result=randomDie(sides),id=++rollSequence;openDicePalette();presentRoll(`d${sides} → ${result}`,id);void deliverRoll(discordPayload(`Бросок d${sides}`,`**${result}**`),id)}
function checkCriticalLabel(check){return check.criticalSuccess?'Критический успех':check.criticalFailure?'Критический провал':''}
function checkOutcome(check){const count=check.success?`Успехов: ${check.successes}`:`Провалов: ${check.failures}`,critical=checkCriticalLabel(check);return `${check.success?'Успех':'Неудача'} · ${count} · УУ ${check.successLevel>=0?'+':''}${check.successLevel}${critical?` · ${critical}`:''}`}
function rollCheck(label,threshold){const check=evaluateD100Check(threshold,randomDie(100)),outcome=checkOutcome(check),critical=checkCriticalLabel(check),id=++rollSequence,fields=[{name:'Итог',value:check.success?'Успех':'Неудача',inline:true},{name:check.success?'Успехи':'Провалы',value:String(check.success?check.successes:check.failures),inline:true},{name:'УУ',value:`${check.successLevel>=0?'+':''}${check.successLevel}`,inline:true}];if(critical)fields.push({name:'Крит',value:critical,inline:false});openDicePalette();presentRoll(`${label}\nd100: ${check.roll} / ${check.target}\n${outcome}`,id);void deliverRoll(discordPayload(`Проверка: ${label}`,`**${check.roll}** / ${check.target}\n${outcome}`,fields),id)}

document.addEventListener('click',event=>{
  if(event.target.dataset.add==='talents'){
    const row=state.talents.at(-1);
    if(row&&!Object.hasOwn(row,'maximumFormula'))Object.assign(row,{taken:1,maximumFormula:'',checks:'',description:'',source:''});
    renderRows('talents');calculate();save();
  }
  const characteristicButton=event.target.closest('[data-roll-characteristic]');
  if(characteristicButton){const key=characteristicButton.dataset.rollCharacteristic,item=CHARACTERISTICS.find(([k])=>k===key);rollCheck(item?.[2]||'Характеристика',charValue(key));return}
  const basicButton=event.target.closest('[data-roll-basic]');
  if(basicButton){const index=num(basicButton.dataset.rollBasic),[name,key]=BASIC_SKILLS[index];rollCheck(name,charValue(key)+num(get(state,`basicSkills.${index}.advances`)));return}
  const advancedButton=event.target.closest('[data-roll-advanced]');
  if(advancedButton){const skill=state.skills[num(advancedButton.dataset.rollAdvanced)];if(skill)rollCheck(skill.name||'Умение',charValue(skill.characteristic)+num(skill.advances))}
});

$('#dice-launch').onclick=openDicePalette;$('#dice-close').onclick=closeDicePalette;$$('[data-die]').forEach(button=>button.onclick=()=>rollPolyhedron(num(button.dataset.die)));
$('#open-discord-dialog').onclick=()=>{const settings=discordSettings();$('#discord-webhook').type='password';$('#toggle-discord-secret').textContent='Показать';$('#discord-webhook').value=settings.webhookUrl;$('#discord-enabled').checked=settings.enabled;$('#discord-status').textContent='';$('#discord-dialog').showModal()};
$('#close-discord-dialog').onclick=()=>$('#discord-dialog').close();$('#discord-dialog').onclick=event=>{if(event.target===$('#discord-dialog'))event.target.close()};
$('#toggle-discord-secret').onclick=()=>{const input=$('#discord-webhook'),visible=input.type==='text';input.type=visible?'password':'text';$('#toggle-discord-secret').textContent=visible?'Показать':'Скрыть'};
$('#discord-form').onsubmit=event=>{event.preventDefault();const webhookUrl=$('#discord-webhook').value.trim(),enabled=$('#discord-enabled').checked;if(webhookUrl&&!validWebhook(webhookUrl)){$('#discord-status').textContent='Проверьте URL: нужен вебхук discord.com/api/webhooks/…';return}if(enabled&&!webhookUrl){$('#discord-status').textContent='Для отправки нужен URL вебхука.';return}localStorage.setItem(DISCORD_STORAGE_KEY,JSON.stringify({enabled,webhookUrl}));updateDiscordIndicator();$('#discord-dialog').close();toast('Настройки Discord сохранены')};
$('#test-discord').onclick=async()=>{const settings={enabled:true,webhookUrl:$('#discord-webhook').value.trim()};if(!validWebhook(settings.webhookUrl)){$('#discord-status').textContent='Сначала вставьте корректный URL вебхука.';return}$('#discord-status').textContent='Отправка…';try{await postDiscord(discordPayload('Проверка подключения','Вебхук WFRP-листа работает.'),settings,true);$('#discord-status').textContent='Сообщение доставлено ✓'}catch(error){$('#discord-status').textContent=`Ошибка: ${error.message}`}};

$$('[data-theme-toggle]').forEach(button=>button.addEventListener('click',toggleTheme));applyTheme(activeTheme(),false);renderCharacteristics();renderBasic();populateClasses();populateCareers('');$('#new-skill-characteristic').innerHTML='<option value="">Выберите характеристику</option>'+CHARACTERISTICS.map(([v,s,n])=>`<option value="${v}">${s} — ${n}</option>`).join('');$('#continue-character').hidden=!localStorage.getItem(STORAGE_KEY);updateDiscordIndicator();
